### ISSUE TITLE
Error: googleapi: Error 403: The bucket you tried to create requires domain ownership verification., forbidden

### ISSUE THREAD

**Issue by MarceloEmmerich** [w3f/polkadot-deployer#148]
Installed as per documentation and have opsgenie, cloudflare and GCP env vars and json files. In GCP, I added a service account and gave this service account owner rights on the domain that is managed in cloudflare. However, when running ```node . create --config config/create.remote.GCP.megahash.json --verbose```, I get the following error:

```
Creating cluster '<my domain>'...


Initializing the backend...

Initializing provider plugins...



Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see

any changes that are required for your infrastructure. All Terraform commands
should now work.


If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other

commands will detect it and remind you to do so if necessary.

google_storage_bucket.imagestore: Creating...



Error: googleapi: Error 403: The bucket you tried to create requires domain ownership verification., forbidden

  on main.tf line 7, in resource "google_storage_bucket" "imagestore":
   7: resource "google_storage_bucket" "imagestore" {



Command execution failed with code: 1

**Comment by MarceloEmmerich** [comment]
Found out what this was about. Having a project name that satisfies a domain regex leads to the above error. Just removed the dot from the project name and it worked.

**Comment by Currycurrycurry** [comment]
@MarceloEmmerich Hi I encountered the similar problem. Did you use the secret json file downloaded from the GCP service account page and set the env variable?
