### ISSUE TITLE
Idea: Live chain integration testing

### ISSUE THREAD

**Issue by jak-pan** [w3f/polkadot-deployer#79]
Hi, I'm Jakub form GalacticCouncil

We're building a DeFi platform that will heavily modify the workings of the chain. Of course we are writing a lot of tests in rust itself but we feel like there is a need for Integration tests running on live chain. We were searching for such tool but couldn't really find anything suitable apart from [mixbytes/tank](https://github.com/mixbytes/tank) which is more of a benchmarking tool not very suitable for local testing, and now we found polkadot-deployer.

We were thinking about slightly modifying this tool to allow easier booting of custom chains and possibly booting local docker images to allow faster development iteration and later using this inside our CI. 

For the testing part, we were thinking about using "benchmarking" part of this tool or writing completely custom tool that will interact with node RPCs using javascript/typescript and measuring desired states.

The question is. What do you think about this?

**Comment by fgimenez** [comment]
Hi Jakub, thx for reaching out and for your interest in polkadot-deployer!

The changes you propose sound interesting, feel free to fork the repo and
start building. For details please read polkadot-deployer license file.

Only one comment, you mention implementing changes to allow creating
networks with local docker images, this is currently possible with
polkadot-deployer, let us know if you need help with this or with anything
else :)

**Comment by fgimenez** [comment]
As an additional note, we have been working on a testing framework that overlaps to some extent with parts of what you propose here. An initial version will be released shortly, I'll post here when it is out.

**Comment by jak-pan** [comment]
Thanks, is it possible to see some progress / details about it anywhere? 
Maybe we're trying to build similar thing so either we could either have some useful input or help with it, if it's similar to what we need.

**Comment by fgimenez** [comment]
For sure, i'll ping you when it is public, probably during the next week.

**Comment by jak-pan** [comment]
@fgimenez hello, just checking out if there is anything new about this.

**Comment by fgimenez** [comment]
Hi @jak-pan sorry for the late response, there are still some pending changes to land, will keep you updated.

**Comment by fgimenez** [comment]
ok! we have finally something out, @jak-pan pls take a look https://github.com/w3f/polkadot-lab minimal functionality but all should work fine. 

We'll keep adding more documentation during this week, especially about test cases, what ones are available now and how to write your own. If anything else is unclear or something doesn't work as expected pls feel free to file issues, PRs are very welcome too :)

**Comment by jak-pan** [comment]
Oh very nice! Looks like it was worth the wait. We’re going to check it out. Thank you.


Jakub Pánik
